apiVersion: v1
kind: Service
metadata:
  name: coredns-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53