apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: cartservice
  name: cartservice
  namespace: hipster-shop
spec:
  loadBalancerSourceRanges: []
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
  selector:
    app: cartservice
  type: ClusterIP
