apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: ilya251188/otus:frontend_v0.0.1
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "PRODUCT_CATALOG_SERVICE"
            - name: CURRENCY_SERVICE_ADDR
              value: "CURRENCY_SERVICE"
            - name: CART_SERVICE_ADDR
              value: "fake"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "fake"
            - name: CHECKOUT_SERVICE_ADDR
              value: "fake"
            - name: SHIPPING_SERVICE_ADDR
              value: "fake"
            - name: AD_SERVICE_ADDR
              value: "fake"