apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: nginx
  
data:
  default.conf: |
    server {
        listen 80 default_server;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
    
    server {
       listen 8080;
    
       location = /basic_status {
           stub_status;
       }
    }